#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Cash {
    AfghanAfghani,          // AFN  ؋
    AlbanianLek,            // ALL  L
    AlgerianDinar,          // DZD  د.ج
    AngolanKwanza,          // AOA  Kz
    ArgentinePeso,          // ARS  $
    ArmenianDram,           // AMD  ֏
    AustralianDollar,       // AUD  $
    AzerbaijaniManat,       // AZN  ₼
    BangladeshiTaka,        // BDT  ৳
    BelarusianRuble,        // BYN  Br
    BolivianBoliviano,      // BOB  Bs.
    BotswanaPula,           // BWP  P
    BrazilianReal,          // BRL  R$
    BritishPound,           // GBP  £
    BurundianFranc,         // BIF  Fr
    CambodianRiel,          // KHR  ៛
    CanadianDollar,         // CAD  $
    ChileanPeso,            // CLP  $
    ChineseYuan,            // CNY  元
    ColombianPeso,          // COP  $
    CongoleseFranc,         // CDF  Fr
    CostaRicanColon,        // CRC  ₡
    CubanPeso,              // CUP  $
    CzechKoruna,            // CZK  Kč
    DominicanPeso,          // DOP  RD$
    EgyptianPound,          // EGP  ج.م
    EthiopianBirr,          // ETB  Br
    Euro,                   // EUR  €
    FijianDollar,           // FJD  $
    GambianDalasi,          // GMD  D
    GeorgianLari,           // GEL  ₾
    GhanaianCedi,           // GHS  ₵
    GuatemalanQuetzal,      // GTQ  Q
    GuineanFranc,           // GNF  Fr
    GuyaneseDollar,         // GYD  $
    HaitianGourde,          // HTG  G
    HonduranLempira,        // HNL  L
    HungarianForint,        // HUF  Ft
    IcelandicKrona,         // ISK  kr
    IndianRupee,            // INR  ₹
    IndonesianRupiah,       // IDR  Rp
    IranianRial,            // IRR  ﷼
    IraqiDinar,             // IQD  ع.د
    IsraeliNewShekel,       // ILS  ₪
    JamaicanDollar,         // JMD  $
    JapaneseYen,            // JPY  円
    KazakhstaniTenge,       // KZT  ₸
    KenyanShilling,         // KES  Sh
    KyrgyzstaniSom,         // KGS  c
    LaoKip,                 // LAK  ₭
    LiberianDollar,         // LRD  $
    LibyanDinar,            // LYD  ل.د
    MalagasyAriary,         // MGA  Ar
    MalawianKwacha,         // MWK  MK
    MalaysianRinggit,       // MYR  RM
    MauritanianOuguiya,     // MRU  UM
    MauritianRupee,         // MUR  Rs
    MexicanPeso,            // MXN  $
    NewZealandDollar,       // NZD  $
    NorthKoreanWon,         // KPW  ₩
    RussianRuble,           // RUB  ₽
    SingaporeDollar,        // SGD  $
    SouthAfricanRand,       // ZAR  R
    SouthKoreanWon,         // KRW  ₩
    SwissFranc,             // CHF  Fr.
    UnitedStatesDollar,     // USD  $
}