#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Cash {
    AfghanAfghani,          // AFN  ؋
    AlbanianLek,            // ALL  L
    AlgerianDinar,          // DZD  د.ج
    AngolanKwanza,          // AOA  Kz
    ArgentinePeso,          // ARS  $
    ArmenianDram,           // AMD  ֏
    AustralianDollar,       // AUD  $
    AzerbaijaniManat,       // AZN  ₼
    BangladeshiTaka,        // BDT  ৳
    BelarusianRuble,        // BYN  Br
    BolivianBoliviano,      // BOB  Bs.
    BotswanaPula,           // BWP  P
    BrazilianReal,          // BRL  R$
    BritishPound,           // GBP  £
    BurundianFranc,         // BIF  Fr
    CambodianRiel,          // KHR  ៛
    CanadianDollar,         // CAD  $
    ChileanPeso,            // CLP  $
    ChineseYuan,            // CNY  元
    ColombianPeso,          // COP  $
    CongoleseFranc,         // CDF  Fr
    CostaRicanColon,        // CRC  ₡
    CubanPeso,              // CUP  $
    CzechKoruna,            // CZK  Kč
    DominicanPeso,          // DOP  RD$
    EgyptianPound,          // EGP  ج.م
    EthiopianBirr,          // ETB  Br
    Euro,                   // EUR  €
    FijianDollar,           // FJD  $
    IndianRupee,            // INR  ₹
    NewZealandDollar,       // NZD  $
    RussianRuble,           // RUB  ₽
    SingaporeDollar,        // SGD  $
    SouthAfricanRand,       // ZAR  R
    UnitedStatesDollar,     // USD  $
}