#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Cash {
    AfghanAfghani,              // AFN  ؋
    AlbanianLek,                // ALL  L
    AlgerianDinar,              // DZD  د.ج
    AngolanKwanza,              // AOA  Kz
    ArgentinePeso,              // ARS  $
    ArmenianDram,               // AMD  ֏
    AustralianDollar,           // AUD  $
    AzerbaijaniManat,           // AZN  ₼
    BangladeshiTaka,            // BDT  ৳
    BelarusianRuble,            // BYN  Br
    BolivianBoliviano,          // BOB  Bs.
    BotswanaPula,               // BWP  P
    BrazilianReal,              // BRL  R$
    BritishPound,               // GBP  £
    BurmeseKyat,                // MMK  Ks
    BurundianFranc,             // BIF  Fr
    CambodianRiel,              // KHR  ៛
    CanadianDollar,             // CAD  $
    ChileanPeso,                // CLP  $
    ChineseYuan,                // CNY  元
    ColombianPeso,              // COP  $
    CongoleseFranc,             // CDF  Fr
    CostaRicanColon,            // CRC  ₡
    CubanPeso,                  // CUP  $
    CzechKoruna,                // CZK  Kč
    DominicanPeso,              // DOP  RD$
    EgyptianPound,              // EGP  ج.م
    EthiopianBirr,              // ETB  Br
    Euro,                       // EUR  €
    FijianDollar,               // FJD  $
    GambianDalasi,              // GMD  D
    GeorgianLari,               // GEL  ₾
    GhanaianCedi,               // GHS  ₵
    GuatemalanQuetzal,          // GTQ  Q
    GuineanFranc,               // GNF  Fr
    GuyaneseDollar,             // GYD  $
    HaitianGourde,              // HTG  G
    HonduranLempira,            // HNL  L
    HungarianForint,            // HUF  Ft
    IcelandicKrona,             // ISK  kr
    IndianRupee,                // INR  ₹
    IndonesianRupiah,           // IDR  Rp
    IranianRial,                // IRR  ﷼
    IraqiDinar,                 // IQD  ع.د
    IsraeliNewShekel,           // ILS  ₪
    JamaicanDollar,             // JMD  $
    JapaneseYen,                // JPY  円
    KazakhstaniTenge,           // KZT  ₸
    KenyanShilling,             // KES  Sh
    KyrgyzstaniSom,             // KGS  c
    LaoKip,                     // LAK  ₭
    LiberianDollar,             // LRD  $
    LibyanDinar,                // LYD  ل.د
    MacedonianDenar,            // MKD  ден
    MalagasyAriary,             // MGA  Ar
    MalawianKwacha,             // MWK  MK
    MalaysianRinggit,           // MYR  RM
    MauritanianOuguiya,         // MRU  UM
    MauritianRupee,             // MUR  Rs
    MexicanPeso,                // MXN  $
    MoldovanLeu,                // MDL  L
    MongolianTogrog,            // MNT  ₮
    MozambicanMetical,          // MZN  MT
    NewTaiwanDollar,            // TWD  $
    NewZealandDollar,           // NZD  $
    NicaraguanCordoba,          // NIO  C$
    NigerianNaira,              // NGN  ₦
    NorthKoreanWon,             // KPW  ₩
    NorwegianKrone,             // NOK  kr
    PakistaniRupee,             // PKR  Rs
    PapuaNewGuineanKina,        // PGK  K
    ParaguayanGuarani,          // PYG  ₲
    PeruvianSol,                // PEN  S/.
    PhilippinePeso,             // PHP  ₱
    PolishZloty,                // PLN  zł
    RomanianLeu,                // RON  lei
    RwandanFranc,               // RWF  Fr
    RussianRuble,               // RUB  ₽
    SamoanTala,                 // WST  T
    SerbianDinar,               // RSD  дин.
    SeychelloisRupee,           // SCR  Rs
    SierraLeoneanLeone,         // SLL  Le
    SingaporeDollar,            // SGD  $
    SolomonIslandsDollar,       // SBD  $
    SomaliShilling,             // SOS  Sh
    SomalilandShilling,         // SLS  Sl
    SouthAfricanRand,           // ZAR  R
    SouthKoreanWon,             // KRW  ₩
    SouthSudanesePound,         // SSP  £
    SriLankanRupee,             // LKR  ரூ
    SudanesePound,              // SDG  ج.س.
    SurinameseDollar,           // SRD  $
    SwedishKrona,               // SEK  kr
    SwissFranc,                 // CHF  Fr.
    SyrianPound,                // SYP  ل.س
    TajikistaniSomoni,          // TJS  с.
    TanzanianShilling,          // TZS  Sh
    ThaiBaht,                   // THB  ฿
    TonganPaAnga,               // TOP  T$
    TransnistrianRuble,         // PRB  p.
    TrinidadandTobagoDollar,    // TTD  $
    TunisianDinar,              // TND  د.ت
    TurkishLira,                // TRY  ₺
    TurkmenistanManat,          // TMT  m.
    UgandanShilling,            // UGX  USh
    UkrainianHryvnia,           // UAH  ₴
    UnitedArabEmiratesDirham,   // AED د.إ
    UnitedStatesDollar,         // USD  $
    UruguayanPeso,              // UYU  $
    UzbekistaniSom,             // UZS  Sʻ
    VanuatuVatu,                // VUV  Vt
    VenezuelanBolivarSoberano,  // VES Bs.
    VietnameseDong,             // VND  ₫
    YemeniRial,                 // YER  ﷼
    ZambianKwacha,              // ZMW  ZK
    RTGSdollar,                 // ZWB  RTGS$
}

impl Cash {
    pub const ALL: [Cash; 116] = [
        Cash::AfghanAfghani,              // AFN  ؋
        Cash::AlbanianLek,                // ALL  L
        Cash::AlgerianDinar,              // DZD  د.ج
        Cash::AngolanKwanza,              // AOA  Kz
        Cash::ArgentinePeso,              // ARS  $
        Cash::ArmenianDram,               // AMD  ֏
        Cash::AustralianDollar,           // AUD  $
        Cash::AzerbaijaniManat,           // AZN  ₼
        Cash::BangladeshiTaka,            // BDT  ৳
        Cash::BelarusianRuble,            // BYN  Br
        Cash::BolivianBoliviano,          // BOB  Bs.
        Cash::BotswanaPula,               // BWP  P
        Cash::BrazilianReal,              // BRL  R$
        Cash::BritishPound,               // GBP  £
        Cash::BurmeseKyat,                // MMK  Ks
        Cash::BurundianFranc,             // BIF  Fr
        Cash::CambodianRiel,              // KHR  ៛
        Cash::CanadianDollar,             // CAD  $
        Cash::ChileanPeso,                // CLP  $
        Cash::ChineseYuan,                // CNY  元
        Cash::ColombianPeso,              // COP  $
        Cash::CongoleseFranc,             // CDF  Fr
        Cash::CostaRicanColon,            // CRC  ₡
        Cash::CubanPeso,                  // CUP  $
        Cash::CzechKoruna,                // CZK  Kč
        Cash::DominicanPeso,              // DOP  RD$
        Cash::EgyptianPound,              // EGP  ج.م
        Cash::EthiopianBirr,              // ETB  Br
        Cash::Euro,                       // EUR  €
        Cash::FijianDollar,               // FJD  $
        Cash::GambianDalasi,              // GMD  D
        Cash::GeorgianLari,               // GEL  ₾
        Cash::GhanaianCedi,               // GHS  ₵
        Cash::GuatemalanQuetzal,          // GTQ  Q
        Cash::GuineanFranc,               // GNF  Fr
        Cash::GuyaneseDollar,             // GYD  $
        Cash::HaitianGourde,              // HTG  G
        Cash::HonduranLempira,            // HNL  L
        Cash::HungarianForint,            // HUF  Ft
        Cash::IcelandicKrona,             // ISK  kr
        Cash::IndianRupee,                // INR  ₹
        Cash::IndonesianRupiah,           // IDR  Rp
        Cash::IranianRial,                // IRR  ﷼
        Cash::IraqiDinar,                 // IQD  ع.د
        Cash::IsraeliNewShekel,           // ILS  ₪
        Cash::JamaicanDollar,             // JMD  $
        Cash::JapaneseYen,                // JPY  円
        Cash::KazakhstaniTenge,           // KZT  ₸
        Cash::KenyanShilling,             // KES  Sh
        Cash::KyrgyzstaniSom,             // KGS  c
        Cash::LaoKip,                     // LAK  ₭
        Cash::LiberianDollar,             // LRD  $
        Cash::LibyanDinar,                // LYD  ل.د
        Cash::MacedonianDenar,            // MKD  ден
        Cash::MalagasyAriary,             // MGA  Ar
        Cash::MalawianKwacha,             // MWK  MK
        Cash::MalaysianRinggit,           // MYR  RM
        Cash::MauritanianOuguiya,         // MRU  UM
        Cash::MauritianRupee,             // MUR  Rs
        Cash::MexicanPeso,                // MXN  $
        Cash::MoldovanLeu,                // MDL  L
        Cash::MongolianTogrog,            // MNT  ₮
        Cash::MozambicanMetical,          // MZN  MT
        Cash::NewTaiwanDollar,            // TWD  $
        Cash::NewZealandDollar,           // NZD  $
        Cash::NicaraguanCordoba,          // NIO  C$
        Cash::NigerianNaira,              // NGN  ₦
        Cash::NorthKoreanWon,             // KPW  ₩
        Cash::NorwegianKrone,             // NOK  kr
        Cash::PakistaniRupee,             // PKR  Rs
        Cash::PapuaNewGuineanKina,        // PGK  K
        Cash::ParaguayanGuarani,          // PYG  ₲
        Cash::PeruvianSol,                // PEN  S/.
        Cash::PhilippinePeso,             // PHP  ₱
        Cash::PolishZloty,                // PLN  zł
        Cash::RomanianLeu,                // RON  lei
        Cash::RwandanFranc,               // RWF  Fr
        Cash::RussianRuble,               // RUB  ₽
        Cash::SamoanTala,                 // WST  T
        Cash::SerbianDinar,               // RSD  дин.
        Cash::SeychelloisRupee,           // SCR  Rs
        Cash::SierraLeoneanLeone,         // SLL  Le
        Cash::SingaporeDollar,            // SGD  $
        Cash::SolomonIslandsDollar,       // SBD  $
        Cash::SomaliShilling,             // SOS  Sh
        Cash::SomalilandShilling,         // SLS  Sl
        Cash::SouthAfricanRand,           // ZAR  R
        Cash::SouthKoreanWon,             // KRW  ₩
        Cash::SouthSudanesePound,         // SSP  £
        Cash::SriLankanRupee,             // LKR  ரூ
        Cash::SudanesePound,              // SDG  ج.س.
        Cash::SurinameseDollar,           // SRD  $
        Cash::SwedishKrona,               // SEK  kr
        Cash::SwissFranc,                 // CHF  Fr.
        Cash::SyrianPound,                // SYP  ل.س
        Cash::TajikistaniSomoni,          // TJS  с.
        Cash::TanzanianShilling,          // TZS  Sh
        Cash::ThaiBaht,                   // THB  ฿
        Cash::TonganPaAnga,               // TOP  T$
        Cash::TransnistrianRuble,         // PRB  p.
        Cash::TrinidadandTobagoDollar,    // TTD  $
        Cash::TunisianDinar,              // TND  د.ت
        Cash::TurkishLira,                // TRY  ₺
        Cash::TurkmenistanManat,          // TMT  m.
        Cash::UgandanShilling,            // UGX  USh
        Cash::UkrainianHryvnia,           // UAH  ₴
        Cash::UnitedArabEmiratesDirham,   // AED د.إ
        Cash::UnitedStatesDollar,         // USD  $
        Cash::UruguayanPeso,              // UYU  $
        Cash::UzbekistaniSom,             // UZS  Sʻ
        Cash::VanuatuVatu,                // VUV  Vt
        Cash::VenezuelanBolivarSoberano,  // VES Bs.
        Cash::VietnameseDong,             // VND  ₫
        Cash::YemeniRial,                 // YER  ﷼
        Cash::ZambianKwacha,              // ZMW  ZK
        Cash::RTGSdollar,                 // ZWB  RTGS$
    ];
}